const KNOWN_COMPANIES: readonly string[] = [
  "10x Genomics",
  "15Five",
  "2K Games",
  "3M",
  "6sense",
  "A. O. Smith",
  "A.T. Kearney",
  "Aaron's",
  "ABB",
  "Abbott Laboratories",
  "AbbVie",
  "ABF Freight",
  "ABN AMRO",
  "Acceldata",
  "Accenture",
  "Accor",
  "Activision Blizzard",
  "Acuity Brands",
  "Adobe Inc.",
  "ADP",
  "ADTRAN",
  "Advance Auto Parts",
  "Advanced Micro Devices",
  "Adyen",
  "AECOM",
  "Aerojet Rocketdyne",
  "AES Corporation",
  "Aetna",
  "Affiliated Managers Group",
  "Affirm",
  "Aflac",
  "AGCO",
  "Agilent Technologies",
  "Agios",
  "Ahana",
  "AIG",
  "Air Products",
  "Airbnb",
  "Airgas",
  "Airtable",
  "Akamai Technologies",
  "Alaska Air Group",
  "Alaska Airlines",
  "Alation",
  "Albemarle Corporation",
  "Albertsons",
  "Alcoa",
  "Aldi",
  "Alexandria Real Estate Equities",
  "Alexion",
  "Alexion Pharmaceuticals",
  "Alibaba",
  "Align Technology",
  "Alkermes",
  "Alleghany",
  "Allegiant Air",
  "Allegion",
  "Allegro MicroSystems",
  "Alliance Data Systems",
  "Alliant Energy",
  "Allianz",
  "Allstate",
  "Ally Financial",
  "Alnylam",
  "Alphabet Inc.",
  "Altria",
  "Amazon",
  "Ambarella",
  "Amcor",
  "AMD",
  "Amerco",
  "Ameren",
  "American Airlines",
  "American Airlines Group",
  "American Electric Power",
  "American Express",
  "American Family Insurance",
  "American Financial Group",
  "American International Group",
  "American Tower",
  "American Water Works",
  "Ameriprise Financial",
  "AmerisourceBergen",
  "Ametek",
  "Amgen",
  "Amphenol",
  "Amplitude",
  "Anadarko Petroleum",
  "Analog Devices",
  "Anduril Industries",
  "Ansys",
  "Anthem",
  "Anthropic",
  "Aon",
  "Aon Hewitt",
  "APA Corporation",
  "Apigee",
  "Apollo Global Management",
  "AppDynamics",
  "Appian",
  "Apple",
  "Applied Industrial",
  "Applied Industrial Technologies",
  "Applied Materials",
  "AppLovin",
  "Aptiv",
  "Aramark",
  "Arcadis",
  "Arch Capital Group",
  "Archer Aviation",
  "Archer Daniels Midland",
  "Arcserve",
  "Ares Management",
  "Argo AI",
  "Arista Networks",
  "Arm Holdings",
  "Armis",
  "Arrow Electronics",
  "Arrowhead Pharmaceuticals",
  "Arthur J. Gallagher",
  "Arup",
  "Asana",
  "ASML",
  "Associated Press",
  "Assurant",
  "AstraZeneca",
  "Astronics",
  "AT&T",
  "Atlan",
  "Atmos Energy",
  "Audacy",
  "Audi",
  "Aurora Innovation",
  "Autodesk",
  "Autoliv",
  "Automatic Data Processing",
  "Automation Anywhere",
  "AutoNation",
  "AutoZone",
  "AvalonBay Communities",
  "Avery Dennison",
  "Avis",
  "Avis Budget Group",
  "Avnet",
  "AXA",
  "Axcient",
  "Axon Enterprise",
  "Axway",
  "Baidu",
  "Bain",
  "Baker Hughes",
  "Ball Corporation",
  "Ballard Power Systems",
  "Bamboo HR",
  "Bank of America",
  "Barclays",
  "Barstool Sports",
  "Bath & Body Works",
  "Baxter International",
  "Bayer",
  "Bazaarvoice",
  "BB&T",
  "Beacon Roofing Supply",
  "Beam Therapeutics",
  "Bechtel",
  "Becton Dickinson",
  "Bed Bath & Beyond",
  "Belden",
  "Berkshire Hathaway",
  "Berry Plastics Group",
  "Best Buy",
  "Best Western",
  "Bethesda",
  "Better",
  "Betterment",
  "Betterworks",
  "Big Lots",
  "BigCommerce",
  "Bio-Rad Laboratories",
  "Bio-Techne",
  "Biogen",
  "BioMarin",
  "BioNTech",
  "Bizagi",
  "Black & Veatch",
  "BlackRock",
  "Blackstone",
  "Blackstone Group",
  "Bleacher Report",
  "Blend",
  "Blizzard Entertainment",
  "Block Inc.",
  "Bloom Energy",
  "Bloomberg",
  "Blue Prism",
  "Blueprint Medicines",
  "BMW",
  "BNP Paribas",
  "BNY Mellon",
  "Boeing",
  "Bombardier",
  "Bombora",
  "Booking Holdings",
  "Booz Allen Hamilton",
  "BorgWarner",
  "Bosch",
  "Boston Consulting Group",
  "Boston Properties",
  "Boston Scientific",
  "Box",
  "Boyd Gaming",
  "BP",
  "Brainware",
  "Brex",
  "Bridgestone",
  "Bristol Myers Squibb",
  "Bristol-Myers Squibb",
  "Broadcom",
  "Broadridge Financial Solutions",
  "Brookfield Asset Management",
  "Brookfield Properties",
  "Brown & Brown",
  "Brown-Forman",
  "Buck Consultants",
  "Budget",
  "Builders FirstSource",
  "Bunge Global",
  "Bungie",
  "Burberry",
  "Burlington",
  "Burlington Stores",
  "Burns & McDonnell",
  "BuzzFeed",
  "BXP Inc.",
  "ByteDance",
  "C.H. Robinson",
  "C.H. Robinson Worldwide",
  "C3.ai",
  "CACI International",
  "Cadence Design Systems",
  "Caesars Entertainment",
  "CalAtlantic Group",
  "Calendly",
  "Calix",
  "Calpine",
  "Camden Property Trust",
  "Campbell Soup",
  "Canon",
  "Canonical",
  "Canoo",
  "Canva",
  "Capgemini",
  "Capital One",
  "Capterra",
  "Carbon Black",
  "Cardinal Health",
  "CarMax",
  "Carnival Corporation",
  "Carnival Cruise Line",
  "Carrier Global",
  "Carta",
  "Carvana",
  "Casey's",
  "Casey's General Stores",
  "Cast Iron Systems",
  "Caterpillar",
  "Cboe Global Markets",
  "CBRE",
  "CBRE Group",
  "CBS",
  "CD Projekt",
  "CDW",
  "CDW Corporation",
  "Celanese",
  "Celgene",
  "Celonis",
  "Cencora",
  "Centene Corporation",
  "CenterPoint Energy",
  "Century 21",
  "Cerebras Systems",
  "Ceridian",
  "CF Industries",
  "Character AI",
  "Charles River Laboratories",
  "Charles Schwab",
  "Charter Communications",
  "Check Point Software",
  "Checkmarx",
  "Chesapeake Energy",
  "Chevron",
  "Chewy",
  "Chime",
  "Chipotle Mexican Grill",
  "Choice Hotels",
  "Chorus",
  "CHS",
  "Chubb",
  "Church & Dwight",
  "Ciena",
  "Cigna",
  "Cimarex Energy",
  "Cincinnati Financial",
  "Cintas",
  "Cirrus Logic",
  "Cisco",
  "Citigroup",
  "Citizens Financial Group",
  "Citrix",
  "Clari",
  "Claroty",
  "Clean Harbors",
  "Clearbit",
  "ClickHouse",
  "Clorox",
  "Cloudera",
  "Cloudflare",
  "CME Group",
  "CMS Energy",
  "Coach",
  "Coca-Cola",
  "Cockroach Labs",
  "Cognizant",
  "Cohere",
  "Coherent",
  "Cohesity",
  "Cohu",
  "Coinbase",
  "Coldwell Banker",
  "Colfax",
  "Colgate-Palmolive",
  "Collibra",
  "Colliers",
  "Comcast",
  "Comerica",
  "Comfort Systems USA",
  "Commercial Metals",
  "CommScope",
  "Community Health Systems",
  "Commvault",
  "Compass",
  "Computer Sciences",
  "Conagra Brands",
  "ConAgra Foods",
  "Condé Nast",
  "Confluent",
  "ConocoPhillips",
  "Consolidated Edison",
  "Constellation Brands",
  "Constellation Energy",
  "Contentsquare",
  "Continental",
  "Continental Resources",
  "Cooper Companies",
  "Cooper Tire & Rubber",
  "Copart",
  "Corelight",
  "CoreWeave",
  "Corning",
  "Corpay",
  "Corteva",
  "CoStar Group",
  "Costco",
  "Coterra Energy",
  "Coty",
  "Covenant Logistics",
  "Cox Automotive",
  "Coyote Logistics",
  "CPI Aerostructures",
  "Cracker Barrel",
  "Crane",
  "Credit Suisse",
  "CRH",
  "CRISPR Therapeutics",
  "CrowdStrike",
  "Crown Castle",
  "Crown Holdings",
  "Cruise",
  "CSX",
  "CSX Corporation",
  "Cubic",
  "Culture Amp",
  "Cummins",
  "Curtiss-Wright",
  "Cushman & Wakefield",
  "CVS Health",
  "Cylance",
  "D.R. Horton",
  "Daiichi Sankyo",
  "Daiwa",
  "Danaher",
  "Darden Restaurants",
  "Darktrace",
  "Dassault Aviation",
  "Databricks",
  "Datadog",
  "DataRobot",
  "Datto",
  "DaVita",
  "dbt Labs",
  "Deckers Brands",
  "Deere",
  "Deere & Company",
  "Dell Boomi",
  "Dell Technologies",
  "Deloitte",
  "Delphi Technologies",
  "Delta Air Lines",
  "Demandbase",
  "Demandware",
  "Denodo",
  "Denso",
  "Dentsply Sirona",
  "Depop",
  "Deutsche Bank",
  "Devon Energy",
  "Dexcom",
  "DHL",
  "Diamondback Energy",
  "DICE",
  "Dick's Sporting Goods",
  "Digital Realty",
  "DigitalOcean",
  "Dillard's",
  "DirecTV",
  "Discord",
  "Discover Financial Services",
  "Discovery Communications",
  "Dish Network",
  "DISH Network",
  "Disney",
  "Disney Cruise Line",
  "DLT Solutions",
  "Dollar General",
  "Dollar Tree",
  "Dominion Energy",
  "Dominion Resources",
  "Domino's",
  "Donaldson",
  "DoorDash",
  "Dover",
  "Dover Corporation",
  "Dow",
  "Dow Chemical",
  "Dr Pepper Snapple Group",
  "Dragos",
  "Dremio",
  "Dresser-Rand",
  "Drift",
  "Dropbox",
  "DRS Technologies",
  "Druid",
  "Druva",
  "DTE Energy",
  "Ducommun",
  "Duke Energy",
  "DuPont",
  "Dynatrace",
  "E*Trade",
  "Eastman Chemical",
  "Eaton",
  "Eaton Corporation",
  "eBay",
  "Echo Global Logistics",
  "EchoStar",
  "Ecolab",
  "Edison International",
  "Editas Medicine",
  "Edwards Lifesciences",
  "Elastic",
  "Elbit Systems",
  "Electronic Arts",
  "Elevance Health",
  "Eli Lilly",
  "Embark Trucks",
  "EMC",
  "Emcor",
  "Emerson Electric",
  "Energen",
  "Energy Transfer",
  "Engility",
  "Enphase Energy",
  "Entergy",
  "Enterprise",
  "Enterprise Products Partners",
  "EOG Resources",
  "Epic Games",
  "EQT",
  "EQT Corporation",
  "Equifax",
  "Equinix",
  "Equity Residential",
  "Ericsson",
  "Erie Indemnity",
  "Erie Insurance",
  "Erwin",
  "ESPN",
  "Essex Property Trust",
  "Estee Lauder",
  "Estes Express",
  "Estée Lauder",
  "Etsy",
  "Everbridge",
  "Everest Group",
  "Evergy",
  "Eversource",
  "Eversource Energy",
  "Exelon",
  "Expedia",
  "Expedia Group",
  "Expeditors International",
  "Express Scripts",
  "Extra Space Storage",
  "ExtraHop",
  "Exxon Mobil",
  "ExxonMobil",
  "EY",
  "F5",
  "Facebook",
  "FactSet",
  "Fair Isaac",
  "Family Dollar",
  "Fannie Mae",
  "Farmers Insurance",
  "Fastenal",
  "Fastly",
  "Federal Realty Investment Trust",
  "FedEx",
  "Ferrari",
  "Ferrellgas Partners",
  "Fiat",
  "Fidelity National Financial",
  "Fidelity National Information Services",
  "Fifth Third Bancorp",
  "Figma",
  "Firebolt",
  "First Data",
  "First Solar",
  "FirstEnergy",
  "Fiserv",
  "Fisker",
  "Five Below",
  "Fivetran",
  "Flex",
  "Flexport",
  "Flight Club",
  "Flowserve",
  "Fluor",
  "Foghorn Therapeutics",
  "Food Lion",
  "Foot Locker",
  "Forbes",
  "Ford Motor",
  "Formfactor",
  "Formstack",
  "Forrester",
  "Fortinet",
  "Fortive",
  "Fortune",
  "Foundation Medicine",
  "Four Seasons",
  "Fox Corporation",
  "Foxconn",
  "Franklin Resources",
  "Fred Meyer",
  "Freddie Mac",
  "Freeport-McMoRan",
  "Freshworks",
  "Frontier Airlines",
  "Frontier Communications",
  "FuelCell Energy",
  "Fujitsu",
  "FullStory",
  "G2",
  "GameStop",
  "Gannett",
  "Gap",
  "Garmin",
  "Gartner",
  "Gatik",
  "GE Aerospace",
  "GE Aviation",
  "GE HealthCare",
  "GE Vernova",
  "Gen Digital",
  "Genentech",
  "Generac",
  "General Atomics",
  "General Dynamics",
  "General Electric",
  "General Growth Properties",
  "General Mills",
  "General Motors",
  "Generali",
  "Genuine Parts",
  "Gevo",
  "Giant Food",
  "Gilead Sciences",
  "Glassbox",
  "Glint",
  "Global Payments",
  "Globe Life",
  "Glu Mobile",
  "GNC Holdings",
  "GOAT",
  "GoDaddy",
  "Goldman Sachs",
  "Gong",
  "Goodyear",
  "Graco",
  "Grafana",
  "Grail",
  "Granite Construction",
  "Graphcore",
  "Gray Television",
  "Graybar Electric",
  "Great Expectations",
  "Green Plains",
  "Greenhouse",
  "Group 1 Automotive",
  "GSK",
  "Guardant Health",
  "Gucci",
  "Gulfstream",
  "Gulfstream Aerospace",
  "Gusto",
  "H&M",
  "H-E-B",
  "H.B. Fuller",
  "Halliburton",
  "Hanesbrands",
  "Harley-Davidson",
  "Hartford Financial Services",
  "Hasbro",
  "HashiCorp",
  "Hasura",
  "Hawaiian Airlines",
  "Hay Group",
  "HCA Healthcare",
  "HCA Holdings",
  "HCL Technologies",
  "HD Supply Holdings",
  "HDR",
  "Healthpeak Properties",
  "Heap",
  "Hearst",
  "Heartland Express",
  "Heartland Payment Systems",
  "Heico",
  "Helmerich & Payne",
  "Henry Schein",
  "Hermes",
  "Hershey",
  "Hertz",
  "Hess",
  "Hewlett Packard Enterprise",
  "Hexion",
  "HF Sinclair",
  "Hilton",
  "Hilton Worldwide",
  "Hitachi",
  "HollyFrontier",
  "Hologic",
  "Home Depot",
  "Honda",
  "Honeywell",
  "Hopper",
  "Hormel Foods",
  "Hortonworks",
  "Host Hotels & Resorts",
  "Hotels.com",
  "Howmet Aerospace",
  "HP",
  "HSBC",
  "Hubbell",
  "HubSpot",
  "Hugging Face",
  "Humana",
  "Huntington Bancshares",
  "Huntington Ingalls Industries",
  "Hy-Vee",
  "Hyatt",
  "HYCU",
  "Hyundai",
  "IBM",
  "IBM API Connect",
  "Icahn Enterprises",
  "ICF",
  "iCIMS",
  "IDC",
  "IDEX",
  "Idexx Laboratories",
  "iHeartMedia",
  "IHG",
  "IKEA",
  "iland",
  "Illinois Tool Works",
  "Illumina",
  "Illumio",
  "Imply",
  "Incyte",
  "Infinity Ward",
  "Inflection AI",
  "Informatica",
  "Infosys",
  "Infrascale",
  "ING",
  "Ingersoll Rand",
  "Ingram Micro",
  "Ingredion",
  "Insight Enterprises",
  "Insilico Medicine",
  "Insperity",
  "Insulet",
  "Intel",
  "Interactive Brokers",
  "Intercom",
  "Intercontinental Exchange",
  "International Flavors & Fragrances",
  "International Paper",
  "Interpublic Group",
  "Intuit",
  "Intuitive Surgical",
  "Invesco",
  "Invitation Homes",
  "IQVIA",
  "Iron Mountain",
  "ITT",
  "J.B. Hunt",
  "J.B. Hunt Transport",
  "J.M. Smucker",
  "Jabil",
  "Jack Henry & Associates",
  "Jacobs",
  "Jacobs Engineering",
  "Jacobs Solutions",
  "Jam City",
  "JetBlue",
  "Jitterbit",
  "JLL",
  "Jobvite",
  "Joby Aviation",
  "Johnson & Johnson",
  "Johnson Controls",
  "Jones Lang LaSalle",
  "JPMorgan Chase",
  "Juniper Networks",
  "K2",
  "Kabam",
  "Kaman",
  "Kansas City Southern",
  "KAR Auction Services",
  "Karuna Therapeutics",
  "Kayak",
  "KB Home",
  "KBR",
  "Keller Williams",
  "Kellogg",
  "Kelly Services",
  "Kennametal",
  "Kenvue",
  "Keurig Dr Pepper",
  "KeyCorp",
  "Keysight Technologies",
  "KEYW Holding",
  "Kia",
  "Kimberly-Clark",
  "Kimco Realty",
  "Kinder Morgan",
  "King",
  "King Soopers",
  "Kirby",
  "KKR",
  "KLA",
  "KLA-Tencor",
  "Klarna",
  "Knight-Swift",
  "Kodiak Robotics",
  "Kofax",
  "Kohl's",
  "Kong",
  "Konica Minolta",
  "KPMG",
  "Kraft Heinz",
  "Krafton",
  "Kratos Defense",
  "Kroger",
  "Kronos",
  "L Brands",
  "L.E.K. Consulting",
  "L3 Technologies",
  "L3Harris",
  "Labcorp",
  "Laboratory Corp. of America",
  "Lacework",
  "Lam Research",
  "Lambda Labs",
  "Lamborghini",
  "Land O'Lakes",
  "Landstar System",
  "LanzaTech",
  "Las Vegas Sands",
  "Lattice",
  "Lattice Semiconductor",
  "Leapsome",
  "Lear",
  "Legg Mason",
  "Leidos",
  "Lennar",
  "Lennox International",
  "Level 3 Communications",
  "Lever",
  "Levi Strauss",
  "LGI Homes",
  "Liberty Mutual Insurance",
  "Lidl",
  "Life Storage",
  "Lincoln Electric",
  "Lincoln National",
  "Linde",
  "Linear",
  "Linode",
  "Lithia Motors",
  "Live Nation",
  "Live Nation Entertainment",
  "LKQ",
  "LoanDepot",
  "Lockheed Martin",
  "Loews",
  "LogRocket",
  "Loom",
  "Lowe's",
  "Lucid Motors",
  "Lululemon Athletica",
  "Lumen Technologies",
  "Lumentum",
  "LVMH",
  "Lyft",
  "LyondellBasell",
  "M&T Bank",
  "MACOM Technology",
  "Macy's",
  "Magellan Midstream Partners",
  "Magento",
  "Magna International",
  "Make",
  "Mandiant",
  "ManpowerGroup",
  "MapR",
  "Marathon Oil",
  "Marathon Petroleum",
  "Marcus & Millichap",
  "Markel",
  "Marqeta",
  "Marriott",
  "Marriott International",
  "Marsh & McLennan",
  "Marsh McLennan",
  "Martin Marietta Materials",
  "Marvell Technology",
  "Masco",
  "Mastercard",
  "Matador Resources",
  "Materialize",
  "Mattel",
  "Maxim Integrated Products",
  "MaxLinear",
  "McAfee",
  "McCormick",
  "McDonald's",
  "McGraw Hill Financial",
  "McKesson",
  "McKinsey",
  "Medallia",
  "Mednax",
  "Medtronic",
  "Meijer",
  "Mendix",
  "Mentor Graphics",
  "Mercari",
  "Mercedes-Benz",
  "Mercer",
  "Merck",
  "Mercury Systems",
  "Meredith",
  "Meritage Homes",
  "Meta Platforms",
  "MetLife",
  "Mettler Toledo",
  "Mettler-Toledo",
  "MGM Resorts",
  "MGM Resorts International",
  "Michaels",
  "Michelin",
  "Microchip Technology",
  "Micron",
  "Micron Technology",
  "Microsoft",
  "Microsoft Gaming",
  "MicroStrategy",
  "Mid-America Apartment Communities",
  "Midjourney",
  "miHoYo",
  "Miro",
  "Mistral AI",
  "Mitsubishi UFJ",
  "Mixpanel",
  "Mizuho",
  "Mobileye",
  "Modal",
  "Moderna",
  "Mohawk Industries",
  "Molina Healthcare",
  "Molson Coors",
  "Monday.com",
  "Mondelez International",
  "MongoDB",
  "Monitor Deloitte",
  "Monolithic Power Systems",
  "Monsanto",
  "Monster Beverage",
  "Monte Carlo",
  "Monzo",
  "Moody's",
  "Moog",
  "Morgan Stanley",
  "Mosaic",
  "Motional",
  "Motive",
  "Motorola Solutions",
  "MSC Cruises",
  "MSC Industrial Direct",
  "MSCI",
  "MTU Aero Engines",
  "Mueller Industries",
  "MuleSoft",
  "Munich Re",
  "Murphy USA",
  "N26",
  "Nasdaq",
  "National Fuel Gas",
  "National Instruments",
  "National Oilwell Varco",
  "National Retail Properties",
  "Nationwide",
  "Natural Grocers",
  "Navan",
  "NBCUniversal",
  "NCC Group",
  "NCSoft",
  "NEC",
  "Neiman Marcus",
  "Neon",
  "Nestle",
  "NetApp",
  "NetEase",
  "Netflix",
  "NetScout Systems",
  "New Relic",
  "New York Life Insurance",
  "New York Times",
  "Newmont",
  "Newmont Mining",
  "News Corp",
  "Nexon",
  "Nexstar Media",
  "NextEra Energy",
  "Niantic",
  "Nike",
  "Nikola",
  "Nintendo",
  "Nintex",
  "NiSource",
  "Nissan",
  "Noble Energy",
  "Nokia",
  "Nomura",
  "Nordson",
  "Nordstrom",
  "Norfolk Southern",
  "Northern Trust",
  "Northrop Grumman",
  "Northwestern Mutual",
  "Norwegian Cruise Line",
  "Notion",
  "Novartis",
  "Novo Nordisk",
  "Nozomi Networks",
  "NPR",
  "NRG Energy",
  "Nubank",
  "Nucor",
  "Nuro",
  "Nutanix",
  "Nvidia",
  "NVR",
  "NXP Semiconductors",
  "O'Reilly Automotive",
  "Occidental Petroleum",
  "OGE Energy",
  "Old Dominion Freight",
  "Old Dominion Freight Line",
  "Old Republic International",
  "Oliver Wyman",
  "Omnicom Group",
  "ON Semiconductor",
  "Oneok",
  "Onsemi",
  "OnSolve",
  "OpenAI",
  "Opendoor",
  "OpenText",
  "OpsGenie",
  "Oracle",
  "Orbital ATK",
  "Orca Security",
  "Oshkosh",
  "Otis Worldwide",
  "Outreach",
  "OutSystems",
  "Ovintiv",
  "Owens Corning",
  "Owens Illinois",
  "PacBio",
  "Paccar",
  "Pacific Life",
  "Packaging Corporation of America",
  "PagerDuty",
  "Palantir",
  "Palantir Technologies",
  "Palo Alto Networks",
  "Panasonic",
  "Pandora",
  "Panera Bread",
  "Paramount",
  "Parker Hannifin",
  "Parsons",
  "Patterson-UTI",
  "Paychex",
  "Paycom",
  "Paylocity",
  "Payoneer",
  "PayPal",
  "PBF Energy",
  "PBS",
  "Peakon",
  "Pearl Abyss",
  "Pegasystems",
  "Penske Automotive",
  "Penske Automotive Group",
  "Pentair",
  "PepsiCo",
  "Peraton",
  "Perceptyx",
  "PerkinElmer",
  "Perplexity AI",
  "Peugeot",
  "Pfizer",
  "PG&E",
  "Philip Morris International",
  "Phillips 66",
  "Piggly Wiggly",
  "Pinnacle West Capital",
  "Pinterest",
  "Pioneer Natural Resources",
  "Plaid",
  "Planet Labs",
  "PlanetScale",
  "Plexus",
  "Plug Power",
  "Plus",
  "PNC Financial Services",
  "Pool Corporation",
  "Porsche",
  "Poshmark",
  "Post Holdings",
  "PostGraphile",
  "PowerReviews",
  "PPG Industries",
  "PPL",
  "Prada",
  "Pratt & Whitney",
  "Precision Castparts",
  "Price Chopper",
  "Priceline",
  "Prime Medicine",
  "Primoris Services",
  "Principal Financial Group",
  "Prisma",
  "Process Street",
  "Procter & Gamble",
  "Progressive",
  "Prologis",
  "Prudential Financial",
  "PTC",
  "Public Service Enterprise Group",
  "Public Storage",
  "Publix",
  "Publix Super Markets",
  "PulteGroup",
  "Pure Storage",
  "PwC",
  "Qorvo",
  "Qualcomm",
  "Qualtrics",
  "Qualys",
  "Quanta Services",
  "Quantum Metric",
  "Quest Diagnostics",
  "R+L Carriers",
  "Rabobank",
  "Rackspace",
  "Radisson",
  "Ralph Lauren",
  "Ralph's",
  "Ramp",
  "Range Resources",
  "Rapid7",
  "Raymond James",
  "Raymond James Financial",
  "Raytheon",
  "RE/MAX",
  "Realty Income",
  "Recursion Pharmaceuticals",
  "Red Hat",
  "Reddit",
  "Redfin",
  "Regency Centers",
  "Regeneron",
  "Regeneron Pharmaceuticals",
  "Regions Financial",
  "Reinsurance Group of America",
  "Relativity Space",
  "Relay Therapeutics",
  "Renault",
  "Renewable Energy Group",
  "Replicate",
  "Republic Services",
  "ResMed",
  "Respawn Entertainment",
  "Reuters",
  "Revolut",
  "Revolution Medicines",
  "Rexnord",
  "Reynolds American",
  "Ribbon Communications",
  "Ricoh",
  "RingCentral",
  "Riot Games",
  "Rippling",
  "Rite Aid",
  "Ritz-Carlton",
  "Rivian",
  "Robinhood",
  "Roblox",
  "Roche",
  "Rocket Lab",
  "Rockset",
  "Rockstar Games",
  "Rockwell Automation",
  "Rockwell Collins",
  "Roland Berger",
  "Rollins",
  "Rolls-Royce",
  "Roper Technologies",
  "Ross Stores",
  "Royal Caribbean",
  "Royal Caribbean Group",
  "RPC",
  "RTX Corporation",
  "Rubrik",
  "Runway AI",
  "Ryder System",
  "Ryland Group",
  "S&P Global",
  "Safeway",
  "Safran",
  "Saia",
  "SAIC",
  "Salesforce",
  "Salesloft",
  "SambaNova Systems",
  "Samsara",
  "Samsung",
  "Sanderson Farms",
  "Sandisk",
  "Sanmina",
  "Sanofi",
  "SAP",
  "Save-A-Lot",
  "SBA Communications",
  "Scale AI",
  "Schlumberger",
  "Schneider National",
  "Scopely",
  "Scotts Miracle-Gro",
  "Scripps Networks Interactive",
  "Seagate",
  "Seagate Technology",
  "Sears",
  "SecureWorks",
  "Segment",
  "Seiko Epson",
  "Sempra",
  "Sempra Energy",
  "SentinelOne",
  "Sentry Insurance",
  "Sephora",
  "ServiceMaster",
  "ServiceNow",
  "Sharp",
  "Shell",
  "Sherwin-Williams",
  "Shield AI",
  "Shopify",
  "ShopRite",
  "Siemens",
  "Signavio",
  "Silicon Laboratories",
  "Simon Property Group",
  "Sinclair",
  "SingleStore",
  "SiriusXM",
  "Sixt",
  "Skechers",
  "Skyworks Solutions",
  "Slack",
  "SM Energy",
  "SmartRecruiters",
  "Smith Douglas Homes",
  "Smurfit Westrock",
  "Snap",
  "Snap-on",
  "SnapLogic",
  "Snowflake",
  "Snyk",
  "SoFi",
  "SoftBank",
  "Software AG",
  "SolarEdge",
  "Sonic Automotive",
  "Sony",
  "Sony Interactive Entertainment",
  "Sony Pictures",
  "Southern Company",
  "Southwest Airlines",
  "Southwest Gas",
  "Spire Global",
  "Spirent Communications",
  "Spirit AeroSystems",
  "Spirit Airlines",
  "Splunk",
  "Spotify",
  "Sprouts Farmers Market",
  "SPX",
  "Stability AI",
  "Standard Chartered",
  "Stanley Black & Decker",
  "Stantec",
  "Staples",
  "Starbucks",
  "Starburst",
  "Starwood Hotels & Resorts",
  "State Farm Insurance",
  "State Street",
  "Steam",
  "Steel Dynamics",
  "Stellantis",
  "StepZen",
  "Stericycle",
  "Steris",
  "Stitch",
  "StockX",
  "Stop & Shop",
  "Strategy&",
  "Stripe",
  "Stryker",
  "SuccessFactors",
  "Sumitomo Mitsui",
  "Sumo Logic",
  "Sunnova",
  "Sunrun",
  "SunTrust Banks",
  "Supabase",
  "Supercell",
  "Supermicro",
  "SurveyMonkey",
  "SUSE",
  "Swiss Re",
  "Symantec",
  "Synaptics",
  "Synchrony Financial",
  "Synnex",
  "Synopsys",
  "Sysco",
  "T-Mobile",
  "T-Mobile US",
  "T. Rowe Price",
  "Take-Two Interactive",
  "Takeda",
  "Talend",
  "Taleo",
  "Tapestry",
  "Targa Resources",
  "Target",
  "Tata Consultancy Services",
  "Taylor Morrison",
  "TE Connectivity",
  "Tech Data",
  "Tech Mahindra",
  "TechnipFMC",
  "Tegna",
  "Teledyne Technologies",
  "Tempus",
  "Tenable",
  "Tencent",
  "Tenneco",
  "Teradata",
  "Teradyne",
  "Terex",
  "Tesla",
  "Tesoro",
  "Texas Instruments",
  "Texas Pacific Land",
  "Textron",
  "Textron Aviation",
  "The Athletic",
  "The RealReal",
  "Thermo Fisher Scientific",
  "ThredUp",
  "TIAA-CREF",
  "TIBCO",
  "TikTok",
  "Time",
  "Time Warner",
  "TJX",
  "TJX Companies",
  "TKO Group Holdings",
  "Toast",
  "Together AI",
  "Toll Brothers",
  "Toshiba",
  "Total System Services",
  "TotalEnergies",
  "Toyota",
  "Tractor Supply",
  "Trade Desk",
  "Trader Joe's",
  "Trane Technologies",
  "TransDigm",
  "TransDigm Group",
  "TravelCenters of America",
  "Travelers",
  "Travelers Companies",
  "Tray.io",
  "Trend Micro",
  "Treyarch",
  "Tribune Publishing",
  "Trimble",
  "TriNet Group",
  "TripAdvisor",
  "Triumph Group",
  "Truist Financial",
  "Trustpilot",
  "TrustRadius",
  "Trustwave",
  "TSMC",
  "TurnTo",
  "TuSimple",
  "Twenty-First Century Fox",
  "Twilio",
  "Twist Bioscience",
  "Twitch",
  "Tyler Technologies",
  "Typeform",
  "Tyson Foods",
  "U.S. Bancorp",
  "Uber",
  "Ubisoft",
  "UBS",
  "UiPath",
  "UKG",
  "Ulta Beauty",
  "Unilever",
  "Union Pacific",
  "Unisys",
  "United Airlines",
  "United Airlines Holdings",
  "United Continental Holdings",
  "United Natural Foods",
  "United Rentals",
  "United States Steel",
  "United Technologies",
  "UnitedHealth Group",
  "Unitrends",
  "Unity Technologies",
  "Universal",
  "Universal Forest Products",
  "Universal Health Services",
  "UPS",
  "US Foods",
  "USAA",
  "Valeo",
  "Valero Energy",
  "Valve",
  "Vantiv",
  "Vectra AI",
  "Vectrus",
  "Veeam",
  "Veeva Systems",
  "Ventas",
  "Veracode",
  "Vercel",
  "Verisign",
  "Verisk Analytics",
  "Veritas",
  "Veritone",
  "Verizon",
  "Vertex Pharmaceuticals",
  "Vertiv",
  "Vestiaire Collective",
  "Viacom",
  "Viavi Solutions",
  "Vice Media",
  "Victoria's Secret",
  "VictorOps",
  "Vinted",
  "Visa",
  "Visteon",
  "Vistra",
  "VMware",
  "Volkswagen",
  "Volvo",
  "Vonage",
  "Vons",
  "Vornado Realty",
  "Vox Media",
  "VRBO",
  "Vroom",
  "Vulcan Materials",
  "Vultr",
  "W.R. Berkley",
  "W.W. Grainger",
  "Wabtec",
  "Waldorf Astoria",
  "Walgreens",
  "Walmart",
  "Walt Disney",
  "Warner Bros. Discovery",
  "Washington Post",
  "Waste Connections",
  "Waste Management",
  "Waters Corporation",
  "Watts Water",
  "Wayfair",
  "Waymo",
  "Wealthfront",
  "WEC Energy Group",
  "Wegmans",
  "WellCare Health Plans",
  "Wells Fargo",
  "Welltower",
  "Wendy's",
  "Werner Enterprises",
  "West Pharmaceutical Services",
  "Western Digital",
  "Western Union",
  "Weyerhaeuser",
  "Whirlpool",
  "WhiteSource",
  "Whole Foods Market",
  "Williams Companies",
  "Williams-Sonoma",
  "Willis Towers Watson",
  "Windstream",
  "Winn-Dixie",
  "Wipro",
  "Wise",
  "Wiz",
  "Wolfspeed",
  "Wolverine World Wide",
  "WooCommerce",
  "Workato",
  "Workday",
  "Workhorse",
  "WSP",
  "WunderGraph",
  "Wyndham",
  "Wyndham Worldwide",
  "Wynn Resorts",
  "Xcel Energy",
  "Xerox",
  "Xilinx",
  "xMatters",
  "XPO Logistics",
  "Xylem",
  "Yotpo",
  "Yum Brands",
  "Yum! Brands",
  "Zapier",
  "Zara",
  "Zebra Technologies",
  "Zendesk",
  "Zerto",
  "ZF Friedrichshafen",
  "Zillow",
  "Zimmer Biomet",
  "Zions Bancorp",
  "Zoetis",
  "Zoom",
  "ZoomInfo",
  "Zoox",
  "Zscaler",
  "Zurich Insurance",
  "Zynga"
];

function normalize(name: string): string {
  return name
    .toLowerCase()
    .replace(/\.(com|io|co|net|org|ai)\b/g, "")
    .replace(/[.,&']/g, "")
    .replace(/\b(inc|llc|corp|ltd|corporation|incorporated|co|plc|group|holdings|technologies|technology|solutions|services|systems|industries|enterprises|international|company|companies|partners|associates|consulting|capital|management|global|worldwide|networks|communications|digital)\b/g, "")
    .replace(/\(class [ab]\)/gi, "")
    .replace(/\s+/g, " ")
    .trim();
}

const KNOWN_NORMALIZED = new Set(KNOWN_COMPANIES.map(normalize));

export function isKnownCompany(name: string | null | undefined): boolean {
  if (!name) return false;
  return KNOWN_NORMALIZED.has(normalize(name));
}

export { KNOWN_COMPANIES };
